image:
  repository: cgr.dev/du-uds-defenseunicorns/velero-fips
  tag: 1.15.0-dev

kubectl:
  image:
    repository: cgr.dev/du-uds-defenseunicorns/kubectl-fips
    tag: 1.31.4-dev

initContainers:
  - name: velero-plugin-for-aws
    image: cgr.dev/du-uds-defenseunicorns/velero-plugin-for-aws-fips:1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
