name: status-checks
description: "Update Status Checks"

inputs:
  status:
    description: "Status to set on the check, ex: pending, success, failure, error"
    required: true
  sha:
    description: "The SHA for the status check"
    required: true

runs:
  using: composite
  steps:
    - name: Set description based on status
      run: |
        if [[ "${{ inputs.status }}" == "success" ]]; then
          echo "DESCRIPTION=Successful" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "failure" ]]; then
          echo "DESCRIPTION=Failed" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "error" ]]; then
          echo "DESCRIPTION=Cancelled" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "pending" ]]; then
          echo "DESCRIPTION=Running..." >> $GITHUB_ENV
        else
          echo "DESCRIPTION=Unknown status" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Post Status Check
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs)
        job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
          -f "state=${{ input.status }}" \
          -f "target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/$job_id" \
          -f "context=${{ github.job }}" \
          -f "description=$DESCRIPTION"
      shell: bash
