name: status-checks
description: "Update Status Checks"

inputs:
  ghToken:
    description: 'GITHUB_TOKEN'
    required: true
  status:
    description: "Status to set on the check, ex: pending, success, failure, error"
    required: true
  url:
    description: "The URL for the status check run"
    required: true
  name:
    description: "The name of the status check"
    required: true
  repo:
    description: "The owner/repo for the status check"
    required: true
  sha:
    description: "The SHA for the status check"
  

runs:
  using: composite
  steps:
    - name: Set description based on status
      run: |
        if [[ "${{ inputs.status }}" == "success" ]]; then
          echo "DESCRIPTION=Successful" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "failure" ]]; then
          echo "DESCRIPTION=Failed" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "error" ]]; then
          echo "DESCRIPTION=Cancelled" >> $GITHUB_ENV
        elif [[ "${{ inputs.status }}" == "pending" ]]; then
          echo "DESCRIPTION=Running..." >> $GITHUB_ENV
        else
          echo "DESCRIPTION=Unknown status" >> $GITHUB_ENV
      shell: bash
    - name: Post Status Check
      env:
        GH_TOKEN: ${{ inputs.ghToken }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{inputs.repo}}/statuses/${{inputs.sha}} \
          -f "state=${{inputs.status}}" -f "target_url=${{inputs.url}}" -f "context=${{inputs.name}}" -f "description=$DESCRIPTION"
      shell: bash
