name: PR Trigger

on:
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:        
      - run: echo "${{ github.event.pull_request.head.sha }}" >> pr_sha.txt

      - name: Upload PR number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_info
          path: pr_sha.txt
