name: Publish UDS Core

on:
  # triggered by tag-and-release.yaml and snapshot-release.yaml
  workflow_call:
    inputs:
      snapshot:
        description: 'true - for snapshot release'
        required: true
        type: boolean

jobs:
  publish-uds-core-layers:
    if: ${{ !inputs.snapshot }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
        layer: [base, identity-authorization]
        arch: [amd64, arm64]
        exclude:
          - flavor: registry1
            arch: arm64
    runs-on: ${{ matrix.arch == 'arm64' && 'macos-latest' || 'ubuntu-latest' }}
    name: Publish package layers

    permissions:
      contents: read
      packages: write
      id-token: write  # This is needed for OIDC federation.

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Publish Core Package Layer
        run: uds run -f tasks/publish.yaml single-layer --set FLAVOR=${{ matrix.flavor }} --set LAYER=${{ matrix.layer }} --no-progress

      - name: Debug Output
        if: ${{ always() && !inputs.snapshot }}
        uses: ./.github/actions/debug-output

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -${{ matrix.flavor }}-${{ matrix.layer }}
