name: lint-check
description: "Check Project for Linting Errors"

runs:
  using: composite
  steps:
    - name: Use Node.js latest
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 20
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install UDS CLI
      # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
      run: brew install defenseunicorns/tap/uds@0.16.0
      shell: bash
    - name: Run Formatting Checks
      run: uds run lint-check --no-progress
      shell: bash
